from typing import Dict, Any
from .config import AnalysisResult

def format_external_scripts(js_info: Dict[str, Any]) -> str:
    """외부 스크립트 도메인 정보를 포맷팅"""
    if not js_info or 'external_scripts' not in js_info or 'count_by_domain' not in js_info['external_scripts']:
        return "     * No external scripts found"
    
    domains = js_info['external_scripts']['count_by_domain']
    return '\n'.join([f"     * {domain}: {count} scripts" for domain, count in domains.items()])

def generate_prompt(url: str, result: AnalysisResult) -> str:
    """분석 결과를 바탕으로 프롬프트 생성"""
    prompt = (
        f"URL Threat Analysis Task\n\n"
        f"Target URL: {url}\n\n"
        f"Technical Analysis Summary:\n"
        f"1. Domain Information:\n"
        f"   - Domain: {result.domain_info.domain}\n"
        f"   - TLD: {result.domain_info.tld}\n"
        f"   - Creation Date: {result.domain_info.whois_info.get('creation_date')}\n"
        f"   - Registrar: {result.domain_info.whois_info.get('registrar')}\n"
        f"   - DNS Records:\n"
        f"     * A Records: {result.domain_info.dns_records['A']['count']} records\n"
        f"     * IPv6 Support: {result.domain_info.dns_records['analysis']['has_ipv6']}\n"
        f"     * MX Records: {result.domain_info.dns_records['analysis']['has_mx']}\n"
        f"     * Total DNS Records: {result.domain_info.dns_records['analysis']['total_records']}\n\n"
        f"2. Security Implementation:\n"
        f"   - SSL Certificate:\n"
        f"     * Issuer: {result.security_info.ssl_certificate.get('issuer', {}).get('organizationName')}\n"
        f"     * Valid Until: {result.security_info.ssl_certificate.get('notAfter')}\n"
        f"     * Issued On: {result.security_info.ssl_certificate.get('notBefore')}\n"
        f"   - Security Headers:\n"
        f"     * HSTS: {result.security_info.security_features.get('has_hsts')} (Valid: {result.security_info.security_features.get('is_hsts_valid')})\n"
        f"     * CSP: {result.security_info.security_features.get('has_csp')}\n"
        f"     * XSS Protection: {result.security_info.security_features.get('has_xss_protection')} (Mode: {result.security_info.security_features.get('xss_protection_mode')})\n"
        f"     * X-Frame-Options: {result.security_info.security_features.get('xframe_policy')}\n\n"
        f"3. Content Analysis:\n"
        f"   - Page Title: {result.content_info.title}\n"
        f"   - JavaScript Security:\n"
        f"     * Total Scripts: {result.content_info.javascript_info.get('script_count')}\n"
        f"     * External Scripts: {result.content_info.javascript_info.get('external_script_count')}\n"
        f"     * Inline Scripts: {result.content_info.javascript_info.get('inline_script_count')}\n"
        f"     * Risk Level: {result.content_info.javascript_info.get('risk_assessment', {}).get('risk_level')}\n"
        f"     * Risk Score: {result.content_info.javascript_info.get('risk_assessment', {}).get('score'):.2f}/10\n"
        f"   - Resource Analysis:\n"
        f"     * External Resources: {len(result.content_info.external_resources)}\n"
        f"     * Forms Present: {len(result.content_info.forms)}\n"
        f"     * Login Form: {result.content_info.has_login_form}\n\n"
        f"4. URL Structure:\n"
        f"   - Length: {result.url_structure['length']}\n"
        f"   - Contains IP: {result.url_structure['ip_in_url']}\n"
        f"   - Abnormal Characters: {result.url_structure['abnormal_chars']}\n"
        f"   - Query Parameters: {result.url_structure['num_params']}\n\n"
        f"Phishing Detection Guidelines:\n\n"
        f"1. Domain Age and Registration Analysis:\n"
        f"   - CRITICAL: Domains less than 6 months old are HIGH risk\n"
        f"   - CRITICAL: Domain age vs SSL certificate age discrepancy indicates potential phishing\n"
        f"   - HIGH RISK: Recently registered domains with business/financial content\n"
        f"   - HIGH RISK: Domains with suspicious keywords or brand similarities\n\n"
        f"2. Security Implementation Assessment:\n"
        f"   - CRITICAL: Complete absence of security headers on business/financial sites\n"
        f"   - HIGH RISK: Free SSL certificates on business/financial sites\n"
        f"   - HIGH RISK: Minimal DNS records on business/financial sites\n"
        f"   - HIGH RISK: Missing HTTPS or invalid certificates\n\n"
        f"3. Content Analysis Patterns:\n"
        f"   - SUSPICIOUS: Generic business descriptions ('innovative solutions', 'empowering business')\n"
        f"   - SUSPICIOUS: Professional claims on newly registered domains\n"
        f"   - HIGH RISK: Login forms on new domains\n"
        f"   - HIGH RISK: Mismatched content vs domain purpose\n\n"
        f"4. Technical Red Flags:\n"
        f"   - CRITICAL: IP addresses in URL\n"
        f"   - CRITICAL: Abnormal URL characters\n"
        f"   - HIGH RISK: Excessive number of redirects\n"
        f"   - HIGH RISK: Obfuscated JavaScript\n\n"
        f"Risk Level Matrix:\n"
        f"1. CRITICAL Risk Indicators (Automatic HIGH Risk Classification):\n"
        f"   - Domain less than 6 months old + Business/Financial content\n"
        f"   - Missing all security headers + Login forms\n"
        f"   - IP address in URL or abnormal characters\n"
        f"   - Domain age vs SSL certificate significant mismatch\n\n"
        f"2. HIGH Risk Indicators (Requires Multiple):\n"
        f"   - Free SSL certificate + Business claims\n"
        f"   - Minimal DNS records + Professional content\n"
        f"   - Missing security headers + External scripts\n"
        f"   - Generic business terms + New domain\n\n"
        f"3. SUSPICIOUS Indicators (Requires Investigation):\n"
        f"   - Some security measures missing\n"
        f"   - Generic business descriptions\n"
        f"   - Limited technical implementation\n"
        f"   - Recent domain registration\n\n"
        f"Classification Guidelines:\n"
        f"- PHISHING: Any CRITICAL indicator or multiple HIGH risk indicators\n"
        f"- SUSPICIOUS: Multiple HIGH risk indicators or many SUSPICIOUS indicators\n"
        f"- LEGITIMATE: No CRITICAL indicators and minimal HIGH risk indicators\n\n"
        f"Risk Level Assignment:\n"
        f"- HIGH: Any CRITICAL indicator or multiple HIGH risk indicators\n"
        f"- MEDIUM: Multiple SUSPICIOUS indicators but no CRITICAL indicators\n"
        f"- LOW: Only for established domains with proper security implementations\n\n"
        f"Provide your analysis in this exact format:\n\n"
        f"<classification>\n"
        f"status: [PHISHING/SUSPICIOUS/LEGITIMATE]\n"
        f"reason: [One sentence focusing on the most critical security finding]\n"
        f"</classification>\n\n"
        f"<security_assessment>\n"
        f"ssl: [One sentence about SSL/TLS implementation and credibility]\n"
        f"headers: [One sentence about security headers and their implications]\n"
        f"content: [One sentence about content security and risk factors]\n"
        f"</security_assessment>\n\n"
        f"<findings>\n"
        f"1. title: [Most critical finding title]\n"
        f"   detail: [One sentence explanation]\n"
        f"2. title: [Second most critical finding title]\n"
        f"   detail: [One sentence explanation]\n"
        f"3. title: [Third most critical finding title]\n"
        f"   detail: [One sentence explanation]\n"
        f"</findings>\n\n"
        f"<risk_assessment>\n"
        f"level: [HIGH/MEDIUM/LOW]\n"
        f"reason: [Two sentence maximum justification based on the risk matrix]\n"
        f"</risk_assessment>\n\n"
        f"<recommendations>\n"
        f"1. [Most critical security improvement needed]\n"
        f"2. [Second most critical security improvement needed]\n"
        f"3. [Third most critical security improvement needed]\n"
        f"</recommendations>"
    )
    return prompt